
name: Build and Push to Docker Hub

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t qunikamshreyas/687153b85887adf827c47db5_streamlit_app:latest .

      - name: Push Docker image
        run: |
          docker push qunikamshreyas/687153b85887adf827c47db5_streamlit_app:latest
